from abc import ABC

from View.UI.Colors import Colors


class UITheme(ABC):
    BACKGROUND_COLOR = (0, 0, 0)
    NODE_COLOR = (0, 0, 0)
    EDGE_COLOR = (0, 0, 0)
    TEXT_WINDOW_BACKGROUND_COLOR = (0, 0, 0)
    MAIN_MENU_BACKGROUND_COLOR = (0, 0, 0)
    MAIN_MENU_LABEL_COLOR = (0, 0, 0)
    MAIN_MENU_SELECTED_LABEL_COLOR = (0, 0, 0)
    SELECTED_NODE_COLOR = (0, 0, 0)
    SELECTED_NODE_SUBTREE_COLOR = (0, 0, 0)
    BARNES_HUT_COLOR = (150, 150, 150, 100)
    FULL_ALPHA = (0, 0, 0, 0)


class BKTheme(UITheme):
    BACKGROUND_COLOR = Colors.ELECTROMAGNETIC
    NODE_COLOR = Colors.HINT_OF_PENSIVE
    EDGE_COLOR = Colors.CHAIN_GANG_GREY
    TEXT_WINDOW_BACKGROUND_COLOR = Colors.HINT_OF_PENSIVE_ALPHA
    MAIN_MENU_BACKGROUND_COLOR = Colors.HINT_OF_PENSIVE_ALPHA
    MAIN_MENU_LABEL_COLOR = Colors.PURE_WHITE
    MAIN_MENU_SELECTED_LABEL_COLOR = Colors.VANADYL_BLUE
    SELECTED_NODE_COLOR = Colors.VANADYL_BLUE
    SELECTED_NODE_SUBTREE_COLOR = Colors.PROTOSS_PYLON
    BARNES_HUT_COLOR = (150, 150, 150, 100)
    FULL_ALPHA = (0, 0, 0, 0)


class MinimalisticTheme:
    BACKGROUND_COLOR = Colors.PURE_WHITE
    NODE_COLOR = Colors.GREY_BLACK
    EDGE_COLOR = Colors.GREY_BLACK
    TEXT_WINDOW_BACKGROUND_COLOR = Colors.GREY_BLACK_ALPHA
    SELECTED_NODE_COLOR = Colors.CONTRAST_RED
    SELECTED_NODE_SUBTREE_COLOR = Colors.CONTRAST_RED

    BARNES_HUT_COLOR = (150, 150, 150, 100)
